Add encoding declaration.
This improves error message with Python 2.

Before:

    $ python demoostrap
      File "demoostrap", line 3
    SyntaxError: Non-ASCII character '\xc2' in file demoostrap on line 3, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

After:

    $ python demoostrap
      File "demoostrap", line 35
        int(0_0)  # Python >= 3.6 is required
              ^
    SyntaxError: invalid syntax